# Generated by Django 5.0.3 on 2024-05-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('student', 'skill_class')},
        ),
    ]
