# Generated by Django 5.0.3 on 2024-05-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_review_unique_together'),
    ]

    operations = [
    ]
